### ISSUE TITLE
Bug when create Contacts through gRPC endpoint

### ISSUE THREAD

**Issue by matmsa27** [Ilhasoft/rapidpro-apps#37]
- When I create an org through the push interface (push-develop.push.al), the contact page works normally
- When I create an org from Connect (dash.weni.ai), the contact page is not working
- The error you're giving is this https://sentry.ilhasoft.mobi/ilhasoft/new-push-dev/issues/217974/?query=is:unresolved
- It seems to me that when creating by GRPC, it is missing to insert the default groups in the org

**Comment by matmsa27** [comment]
see the behavior: https://github.com/rapidpro/rapidpro/blob/7fcec256d08198ceee5caee0dac72c3573457476/temba/orgs/models.py#L1799

**Comment by Sandro-Meireles** [comment]
We fixed the problem and we have already merged into the develop branch: https://github.com/Ilhasoft/rapidpro-apps/pull/39
